[tracing.filters]
default = "debug"
tantivy = "warn"
hyper = "info"

[http]
# address = "0.0.0.0"
port = 8080

[http.admin.auth]
username = "username"
password = "password"

[http.api1.sheet]
limit.default = 100
limit.max = 500
limit.depth = 2
# TODO: should this be shared with search eventually, or nah?
filter.exdschema.list = "Name,Singular,Icon"

[data]
language = "en"

[version]
interval = 3600 # 1 hour
directory = "versions"
repositories = [
  "4e9a232b", # ffxiv
  "6b936f08", # ex1 (hw)
  "f29a3eb2", # ex2 (stb)
  "859d0e24", # ex3 (shb)
  "1bf99b87", # ex4 (ew)
]

[version.thaliak]
endpoint = "https://thaliak.xiv.dev/graphql/2022-08-14"

[version.patch]
directory = "patches"
concurrency = 4
user_agent = "FFXIV PATCH CLIENT"

[schema]
default = "exdschema"
interval = 3600       # 1 hour

[schema.exdschema]
default = "HEAD"
remote = "https://github.com/xivdev/EXDSchema.git"
directory = "exdschema"

[search.pagination]
limit_default = 100
limit_max = 500

[search.tantivy]
directory = "search"
memory = 52428800    # 50MiB

[search.tantivy.cursor]
ttl = 3600 # 1 hour
tti = 300  # 5 minutes
