name: Test and Coverage

on: [push]

jobs:
    test_and_coverage:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      use-cross: false
                      use-tarpaulin: false
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      use-cross: false
                      use-tarpaulin: false
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Run Tests and Upload Coverage
              uses: Reloaded-Project/devops-rust-test-and-coverage@v1
              with:
                  use-cross: ${{ matrix.use-cross }}
                  use-tarpaulin: ${{ matrix.use-tarpaulin }}
                  target: ${{ matrix.target }}
