name: Test and Coverage

on: [push]

jobs:
    run_tests:
        strategy:
            matrix:
                platform:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      use-cross: false
                      use-tarpaulin: false
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      use-cross: false
                      use-tarpaulin: false
        runs-on: ${{ matrix.platform.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Update local toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Add arch specific tooling (optional)
              if: ${{ !contains(matrix.platform.target, 'x86_64-unknown-linux-gnu')}}
              run: |
                  sudo dpkg --add-architecture arm64
                  sudo apt-get update && apt-get install libssl-dev:arm64 gcc-aarch64-linux-gnu
                  rustup target add ${{ matrix.platform.target }}
            - name: Toolchain info
              run: |
                  cargo --version --verbose
                  rustc --version
                  cargo clippy --version
            - name: Lint
              run: |
                  cargo fmt -- --check
                  cargo clippy -- -W warnings
            - name: Test
              run: |
                  cargo check --release --target ${{ matrix.platform.target }} --workspace
                  cargo test --release --target ${{ matrix.platform.target }} --workspace
            - name: Build
              run: cargo build --release --target ${{ matrix.platform.target }} --bin boilmaster
